/* Project Portfolio — project data
   Edit this file to add, remove, or update projects. No build step required. */

const CATEGORIES = [
  { id: 'cybersecurity',  name: 'Cybersecurity Consulting',      code: 'SEC'  },
  { id: 'automation',     name: 'Home Server Automation',        code: 'AUTO' },
  { id: 'ai-assistants',  name: 'AI Assistants & Productivity',  code: 'AI'   },
  { id: 'business-tools', name: 'Business & Lead-Gen Tools',     code: 'BIZ'  },
  { id: 'community',      name: 'Client & Community Projects',   code: 'COM'  },
  { id: 'maker',          name: 'Maker, Radio & Hobby',          code: 'MAKE' },
  { id: 'kids',           name: 'Built for the Kids',            code: 'KID'  },
];

const STATUSES = {
  live:       { label: 'Live' },
  active:     { label: 'Active' },
  prototype:  { label: 'Prototype' },
  concept:    { label: 'Concept' },
  archived:   { label: 'Archived' },
  inprogress: { label: 'In Progress' },
};

const PROJECTS = [
  // ── Cybersecurity Consulting ──────────────────────────────
  {
    id: 'network-assessment',
    name: 'Network Security Assessment Toolkit',
    category: 'cybersecurity',
    status: 'live',
    summary: 'The real scanning-and-reporting engine behind every paid AxiomGate Security Group assessment.',
    whatItIs: "An 11+ module Python pipeline that runs a complete network security assessment end to end: discovers every device on a network, captures traffic, scans for vulnerabilities through an OpenVAS integration, runs credentialed configuration checks over SSH and WinRM, surveys wireless networks and IoT firmware, checks what's exposed to the public internet, checks staff emails against known data breaches, and tests for default or weak credentials. It closes with an automatically generated PDF report — complete with charts and a network diagram — plus separate plain-language walkthroughs for homeowners and for IT managers.",
    problem: "Delivering a thorough, consistent security assessment by hand is slow and easy to make inconsistent as a one-person consultancy. This toolkit turns a multi-day manual process into a repeatable pipeline, so every client gets the same rigor and a professional report without reinventing the process each time.",
    tech: ['Python', 'Nmap', 'Scapy', 'OpenVAS', 'Paramiko', 'ReportLab', 'Claude API'],
    repos: [{ name: 'AxiomGate/Network-Assessment', url: 'https://github.com/AxiomGate/Network-Assessment' }],
    flagship: true,
  },
  {
    id: 'network-collector',
    name: 'Post-Assessment Threat Monitor',
    category: 'cybersecurity',
    status: 'live',
    summary: "A small always-on box that watches a client's network for weeks after an assessment, looking for real signs of compromise.",
    whatItIs: "A lightweight Python agent that runs on a small always-on Linux device — like a Raspberry Pi — dropped at a client site. With a mirrored switch port, it watches DNS activity, checks connections against malware and threat-intel blocklists, statistically detects the 'beaconing' patterns typical of malware phoning home, flags connections to watch-listed countries, and learns each device's normal behavior so it can flag anything unusual. It ships with a live web dashboard, email alerts, and a polished PDF report at the end of the deployment window.",
    problem: "A one-time scan can't prove whether a network is actually compromised — that takes watching real traffic over time, which isn't practical by hand. This automates unattended monitoring for a typical 7-to-30-day window and turns it into a client-ready findings report.",
    tech: ['Python', 'Scapy', 'Flask', 'SQLite', 'MaxMind GeoIP2', 'Leaflet.js'],
    repos: [{ name: 'AxiomGate/Network-Collector', url: 'https://github.com/AxiomGate/Network-Collector' }],
    flagship: true,
  },
  {
    id: 'remediation-guide',
    name: 'Client Remediation Report Generator',
    category: 'cybersecurity',
    status: 'live',
    summary: 'Turns assessment findings into a polished, branded fix-it guide a non-technical client can actually follow.',
    whatItIs: "A pair of generator scripts — one in Python, one in JavaScript — that each produce the same branded \"Internet Exposure Remediation Guide\" as a finished PDF and Word document. It walks a client through fixing specific findings (exposed router management, open DNS, outdated firmware, default credentials, missing VPN) with a risk rating and numbered steps for each.",
    problem: "After an assessment, a client needs something they can actually act on, not a raw findings dump. This produces a professional, consistently branded document automatically instead of writing it by hand for every engagement.",
    tech: ['Python', 'ReportLab', 'Node.js', 'docx'],
    repos: [{ name: 'AxiomGate/Network-Assessment-remediation-guide', url: 'https://github.com/AxiomGate/Network-Assessment-remediation-guide' }],
  },
  {
    id: 'security-onion-course',
    name: 'Security Onion Training Course',
    category: 'cybersecurity',
    status: 'inprogress',
    summary: 'A self-authored training course teaching Security Onion, built as narrated audio paired with hands-on labs.',
    whatItIs: "A planned 15-module curriculum pairing a roughly 30-minute narrated audio script with a hands-on lab guide for each module — covering network security monitoring from philosophy and installation through alert triage and threat hunting. The first several modules are recorded and lab-tested; the rest are in progress.",
    problem: "Learning a complex tool like Security Onion from scratch is slow without structured material. Writing this out forces a systematic understanding and creates something colleagues or clients can learn from too — audio for passive learning, labs for hands-on practice.",
    tech: ['Markdown', 'Piper (local TTS)', 'Docker'],
    repos: [{ name: 'AxiomGate/security-onion-course', url: 'https://github.com/AxiomGate/security-onion-course' }],
  },
  {
    id: 'ooma-ai-receptionist',
    name: 'AI Phone Receptionist',
    category: 'cybersecurity',
    status: 'prototype',
    summary: 'An AI voice agent that answers the business line, explains services, takes messages, and books appointments.',
    whatItIs: "A Node.js server that bridges the AxiomGate business phone line (via Ooma and Twilio) to OpenAI's real-time voice API, so an AI can hold a live spoken conversation with callers. It can explain the consulting services offered, take a structured message, check and book appointments through Calendly, or transfer urgent calls to a real phone.",
    problem: "A one-person consulting business has no receptionist — calls would otherwise go to voicemail or get missed entirely. This answers every call immediately and handles the routine ones automatically.",
    tech: ['Node.js', 'Fastify', 'Twilio', 'OpenAI Realtime API', 'Calendly API'],
    repos: [{ name: 'AxiomGate/ooma-ai-telephone-assistant', url: 'https://github.com/AxiomGate/ooma-ai-telephone-assistant' }],
  },
  {
    id: 'biz-dev-radars',
    name: 'Business Development Radar Suite',
    category: 'cybersecurity',
    status: 'prototype',
    summary: 'Three watchers that turn public data — breach disclosures, government contracts, new regulations — into sales and compliance leads.',
    whatItIs: "A trio of small Python tools built as genericized, shareable versions of AxiomGate's internal lead-generation scripts: one watches SEC filings for newly disclosed corporate data breaches (a natural moment to offer security help), one watches SAM.gov for government contract opportunities matching chosen keywords, and one watches the Federal Register for new cybersecurity, AI, and privacy regulations before they take effect. Each posts new matches to Discord and ships with its own guided setup wizard.",
    problem: "Watching SEC filings, government contract boards, and federal regulations by hand every day doesn't scale for a small consultancy. These automate the watching so new opportunities and compliance deadlines surface on their own.",
    tech: ['Python', 'SEC EDGAR API', 'SAM.gov API', 'Federal Register API', 'Discord webhooks'],
    repos: [
      { name: 'AxiomGate/local-breach-lead-radar', url: 'https://github.com/AxiomGate/local-breach-lead-radar' },
      { name: 'AxiomGate/local-gov-contract-radar', url: 'https://github.com/AxiomGate/local-gov-contract-radar' },
      { name: 'AxiomGate/local-compliance-radar', url: 'https://github.com/AxiomGate/local-compliance-radar' },
    ],
  },
  {
    id: 'axiomgate-company-site',
    name: 'AxiomGate Security Group — Company Website',
    category: 'cybersecurity',
    status: 'prototype',
    summary: 'The marketing site for the cybersecurity consulting business itself — services, process, and booking.',
    whatItIs: "A plain HTML/CSS/JS marketing site covering the AxiomGate Security Group story, its residential and SMB network-assessment service tiers, a six-step \"how it works\" walkthrough, and a booking/contact flow — plus a minimal public landing page for the GitHub organization profile.",
    problem: "A consulting business needs a professional web presence that explains what it does, who it's for, and how to book a call, in plain language rather than security jargon.",
    tech: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    repos: [
      { name: 'AxiomGate/axiom-gate-website', url: 'https://github.com/AxiomGate/axiom-gate-website' },
      { name: 'AxiomGate/axiomgate', url: 'https://github.com/AxiomGate/axiomgate' },
    ],
  },

  // ── Home Server Automation ────────────────────────────────
  {
    id: 'digest-network',
    name: 'Local Intelligence Digest Network',
    category: 'automation',
    status: 'live',
    summary: 'A fleet of ~20 bots that watch different topics all day and post digest summaries to Discord — cybersecurity, DevOps, ham radio, AI models, GPU deals, and more.',
    whatItIs: "A family of small, single-purpose Python scripts sharing one architecture: fetch real data from RSS feeds and public APIs first, then — only optionally — let a locally-run AI model turn the facts into a short written summary. The AI is never allowed to invent the underlying facts or dates, only phrase them. Individual bots cover actively-exploited vulnerabilities, network-vendor security advisories, DevOps tool releases, local ham radio events, local kids' STEM events, GPU hardware deals, and new open-source AI model releases (tracked two different ways). All of them run as scheduled, disposable Docker containers on a home server, and the whole fleet is orchestrated together in a private production repo.",
    problem: "Manually checking a dozen unrelated sources every day for what's new doesn't scale, and an earlier attempt at having a local AI model simply \"research\" these topics on its own produced hallucinated, made-up results. Keeping data-fetching deterministic and code-based — with AI used only for prose — gets the convenience of a daily briefing without trusting an AI to get the facts right.",
    tech: ['Python', 'feedparser', 'Discord webhooks', 'Ollama', 'Docker', 'cron'],
    repos: [{ name: 'AxiomGate/axiomgate-briefs (fleet)', url: 'https://github.com/AxiomGate/axiomgate-briefs' }],
    variants: [
      { name: 'Cyber Exploit Brief', url: 'https://github.com/AxiomGate/local-daily-cyber-brief', note: 'CISA KEV + top security news' },
      { name: 'Network Security Digest', url: 'https://github.com/AxiomGate/local-network-security-digest', note: 'Vendor PSIRT advisories (Cisco, Fortinet, Palo Alto)' },
      { name: 'Tech Morning Brief', url: 'https://github.com/AxiomGate/local-tech-morning-brief', note: 'DevOps tool releases + Hacker News' },
      { name: 'Ham Radio Digest', url: 'https://github.com/AxiomGate/local-ham-radio-digest', note: 'Local club meetings, hamfests, nets' },
      { name: "Kids' STEM Digest", url: 'https://github.com/AxiomGate/local-kids-stem-digest', note: 'Local STEM / tech / music events for kids' },
      { name: 'GPU Deal Watch', url: 'https://github.com/AxiomGate/local-gpu-deal-watch', note: 'Underpriced AI-capable GPUs on Craigslist/Reddit/eBay' },
      { name: 'Open Model Radar', url: 'https://github.com/AxiomGate/local-model-radar', note: 'New open AI models that fit your GPU' },
      { name: 'Open Models Digest', url: 'https://github.com/AxiomGate/local-open-models-digest', note: 'Weekly top-3-per-category open model ranking' },
      { name: 'Model Digest Worker', url: 'https://github.com/AxiomGate/model-digest-worker', note: 'A/B variant of the open-models ranking pipeline' },
    ],
    flagship: true,
  },
  {
    id: 'podcast-worker',
    name: 'Automated Daily Podcast Pipeline',
    category: 'automation',
    status: 'live',
    summary: 'Turns the daily digest briefs into a fully-produced two-host podcast video with zero manual editing.',
    whatItIs: "A Dockerized pipeline that watches for new Markdown briefing files, has a local AI model write a two-host, five-minute script, synthesizes each host's lines with distinct text-to-speech voices, mixes in intro and outro music, and renders a finished 1080p video — optionally uploading it straight to YouTube.",
    problem: "Turning a stack of text briefs into listenable audio or video is normally a manual recording-and-editing job. This closes the loop on the digest network above: a text brief becomes a finished episode with no hands-on production time, running unattended on home-server hardware.",
    tech: ['Python', 'Docker', 'Ollama', 'Piper / Chatterbox TTS', 'FFmpeg', 'YouTube API'],
    repos: [{ name: 'AxiomGate/daily-podcast-worker', url: 'https://github.com/AxiomGate/daily-podcast-worker' }],
  },
  {
    id: 'pi-calendar',
    name: 'Family Calendar Dashboard',
    category: 'automation',
    status: 'live',
    summary: "An always-on wall display that merges a family's Outlook and Google calendars into one glanceable view.",
    whatItIs: "A Flask web app running in fullscreen kiosk mode on a Raspberry Pi wired to a wall-mounted monitor. It pulls events from both a Microsoft 365 account and a Google account, merges them, color-codes them per family member, and auto-cycles through Month, Week, Day, and \"next 4 hours\" views with a live countdown to what's next.",
    problem: "A family split across two calendar providers has no single glanceable view of what's coming up — especially for family members with no calendar account of their own. One always-on shared display replaces checking separate apps.",
    tech: ['Python', 'Flask', 'Microsoft Graph API', 'Google Calendar API', 'Raspberry Pi', 'Chromium kiosk'],
    repos: [{ name: 'AxiomGate/pi-calendar-dashboard', url: 'https://github.com/AxiomGate/pi-calendar-dashboard' }],
  },
  {
    id: 'google-home-guard',
    name: 'Smart Thermostat Guardrail',
    category: 'automation',
    status: 'live',
    summary: "A tiny script that keeps one room's smart thermostat from ever getting left too cold.",
    whatItIs: "A dependency-free Python script that checks every Nest thermostat in the house via Google's Smart Device Management API and raises any heating setpoint found below 72°F back up — never lowering one, and skipping units that are off or in cooling mode. It runs every 10 minutes via a scheduled task.",
    problem: "One zone of the house kept drifting below a comfortable minimum with no built-in way in the Nest app to enforce a floor automatically. This closes that gap without buying a third-party smart-home hub.",
    tech: ['Python', 'Google Smart Device Management API', 'cron'],
    repos: [{ name: 'AxiomGate/Google-home', url: 'https://github.com/AxiomGate/Google-home' }],
  },
  {
    id: 'nas-cleaner',
    name: 'NAS Duplicate File Cleaner',
    category: 'automation',
    status: 'active',
    summary: 'Finds and safely removes duplicate files on a home NAS, and can auto-sort media into the right folders.',
    whatItIs: "A Windows desktop tool that scans a NAS share for files sharing the same name and size, decides which copy to keep, and always produces a dry-run report before deleting anything — cleanup requires an explicit confirmation. A companion mode proposes sorting movies, shows, books, music, and photos into proper library folders, with optional local-AI help for ambiguous files.",
    problem: "A large NAS share accumulates duplicate files and disorganized media over time. This reclaims wasted space safely — a reviewable dry run, never a blind bulk delete — and auto-organizes a messy media dump.",
    tech: ['Python', 'SQLite', 'Ollama'],
    repos: [{ name: 'AxiomGate/nas-duplicate-cleaner', url: 'https://github.com/AxiomGate/nas-duplicate-cleaner' }],
  },
  {
    id: 'ops-sentinel',
    name: 'Fleet-Wide Error Monitoring',
    category: 'automation',
    status: 'live',
    summary: 'The watchdog that reads error logs from every other automated project here and reports problems in one place.',
    whatItIs: "A central monitoring service that every other home-server script and bot reports small, redacted, structured events to. It classifies incoming events, posts a nightly summary to Discord, sends instant alerts on individual errors, and — only when manually triggered and explicitly allow-listed per project — can draft or apply a safe automated fix.",
    problem: "Running dozens of independent, unattended scripts means errors can pile up silently in scattered logs with nobody noticing. This centralizes visibility across the whole fleet, while deliberately keeping raw log content away from any AI model and keeping automated fixes behind a manual, opt-in trigger.",
    tech: ['Python', 'YAML', 'Discord webhooks', 'Docker'],
    repos: [{ name: 'AxiomGate/ops-sentinel', url: 'https://github.com/AxiomGate/ops-sentinel' }],
  },

  // ── AI Assistants & Productivity ──────────────────────────
  {
    id: 'email-assistant',
    name: 'Local AI Inbox Assistant',
    category: 'ai-assistants',
    status: 'active',
    summary: 'Clears junk out of an inbox and drafts replies to what matters — but never sends anything on its own.',
    whatItIs: "A CLI tool that connects to Gmail and/or Outlook, archives and labels junk mail per editable rules, and uses a locally-hosted AI model to draft replies to VIP senders or important unread messages — saved to Drafts for a human to review and send. Every command defaults to a dry-run preview, and both junk-sweeping and draft-writing are safe to re-run.",
    problem: "Triaging a busy inbox and remembering to reply to what matters is tedious. This automates the sorting and hands back a ready-to-edit draft instead of a blank page — with hard safety limits (no send permission, no delete permission, local-only AI) built in by design, not as an afterthought.",
    tech: ['Python', 'Gmail API', 'Microsoft Graph API', 'Ollama'],
    repos: [{ name: 'AxiomGate/email-assistant', url: 'https://github.com/AxiomGate/email-assistant' }],
  },
  {
    id: 'personal-tasks-app',
    name: 'Self-Hosted Task & Notes App',
    category: 'ai-assistants',
    status: 'prototype',
    summary: 'A private, self-hosted alternative to juggling a to-do app, a notes app, and a calendar app.',
    whatItIs: "A full-stack web app — FastAPI backend, vanilla JS frontend, SQLite storage — with login, task management with priorities and due dates, note-taking, and calendar events, all scoped to a logged-in user.",
    problem: "For someone who wants their personal task and note data off Google, Microsoft, or Notion's servers, this replaces three separate apps with one lightweight, self-hosted tool under their own control.",
    tech: ['Python', 'FastAPI', 'SQLAlchemy', 'SQLite', 'JavaScript'],
    repos: [{ name: 'AxiomGate/personal-ai-assistant1', url: 'https://github.com/AxiomGate/personal-ai-assistant1' }],
  },
  {
    id: 'interview-prep-rag',
    name: 'Interview Prep Coach',
    category: 'ai-assistants',
    status: 'prototype',
    summary: 'Turns a resume and a job posting into personalized practice questions and coaching material for a cybersecurity interview.',
    whatItIs: "A CLI tool backed by a local, reusable knowledge base. It takes a candidate's resume and a specific job posting, extracts the role's requirements, and searches its knowledge base for relevant material before calling any AI service — then generates knowledge quizzes, coaching scripts, review packets, and spoken study audio targeted at the candidate's actual weak spots.",
    problem: "Coaching a candidate for a technical interview usually means re-researching the same recurring topics from scratch every time. A reusable local knowledge base carries prior research forward to the next client, and quizzing first means the deeper material goes where it's actually needed.",
    tech: ['Python', 'SQLite (FTS5)', 'OpenAI API'],
    repos: [{ name: 'AxiomGate/interview-prep-rag', url: 'https://github.com/AxiomGate/interview-prep-rag' }],
  },
  {
    id: 'voice-checkin',
    name: 'Voice Daily Check-In',
    category: 'ai-assistants',
    status: 'concept',
    summary: 'An early proof-of-concept for a spoken daily companion that helps track appointments, tasks, and how the day actually went.',
    whatItIs: "A detailed spec for a voice-first daily check-in app — talk freely about your day, it summarizes what it heard, extracts appointments and tasks, asks clarifying questions, and builds a plan for tomorrow, with an explicit crisis-safety boundary. The working code so far is a small browser proof-of-concept testing the listening-and-talking interaction using the browser's built-in speech APIs.",
    problem: "Staying on top of daily commitments and emotional load by talking them through — the way you might with a coach — instead of typing into a task app. Meant to gently follow up on things that didn't happen and help figure out whether the blocker was practical, emotional, or just unclear.",
    tech: ['Node.js', 'Web Speech API', 'JavaScript'],
    repos: [{ name: 'AxiomGate/voice-support-prototype', url: 'https://github.com/AxiomGate/voice-support-prototype' }],
  },
  {
    id: 'hermes-docker',
    name: 'Sandboxed AI Agent Runtime',
    category: 'ai-assistants',
    status: 'active',
    summary: 'A locked-down container that runs a third-party autonomous AI agent without giving it access to anything by default.',
    whatItIs: "A Docker Compose setup that installs and runs Hermes Agent — an autonomous AI agent product from Nous Research, not built here — in a tightly sandboxed container. By default the agent has no access to the host's files or the Docker engine, is reachable only from the same machine, and gains extra access only one deliberate step at a time, plus a couple of small custom skills layered on top, like home-network device discovery.",
    problem: "Autonomous AI agents that can take their own actions are risky to run with broad access to a personal computer. This makes one usable day-to-day while keeping it isolated unless a specific hole is deliberately opened — a working example of least-privilege thinking applied to untrusted software, not a security add-on bolted on after the fact.",
    tech: ['Docker Compose', 'WSL2', 'PowerShell'],
    repos: [{ name: 'AxiomGate/hermes-docker', url: 'https://github.com/AxiomGate/hermes-docker' }],
    note: 'The AI agent itself is a third-party product (Nous Research); the sandboxing and hardening around it is the original work.',
  },

  // ── Business & Lead-Gen Tools ─────────────────────────────
  {
    id: 'homeowner-lead-radar',
    name: 'Homeowner Mailing List Builder',
    category: 'business-tools',
    status: 'active',
    summary: 'Give it a business address and a radius, and it builds a spreadsheet of every nearby homeowner for direct-mail marketing.',
    whatItIs: "A CLI tool that geocodes a business address and pulls every residential property within a radius from county public tax-assessment records, exporting a two-tab spreadsheet (individual owners vs. LLC-owned rentals) sorted by property value.",
    problem: "Small businesses want to mail postcards to nearby homeowners but have no easy way to get an accurate, current list of who lives nearby, short of buying an expensive third-party mailing list.",
    tech: ['Python', 'US Census Geocoding API', 'County GIS data', 'Excel export'],
    repos: [{ name: 'AxiomGate/homeowner-lead-radar', url: 'https://github.com/AxiomGate/homeowner-lead-radar' }],
  },
  {
    id: 'biz-market-scout',
    name: 'Local Market Competitor Scout',
    category: 'business-tools',
    status: 'active',
    summary: 'Give it a business type and a city, and it profiles every matching business nearby, including who owns it.',
    whatItIs: "A CLI tool that discovers every business of a given type within a radius using free map data, then optionally uses Claude's web-search tool to research each one further — owner's name, years in business, BBB accreditation — exporting it all to a spreadsheet.",
    problem: "Sizing up local competition or building a prospect list normally means manually researching every business in an area one at a time. This automates that into one spreadsheet in under an hour.",
    tech: ['Python', 'OpenStreetMap API', 'Claude API (web search)', 'Excel export'],
    repos: [{ name: 'AxiomGate/biz-market-scout', url: 'https://github.com/AxiomGate/biz-market-scout' }],
  },
  {
    id: 'config-forge',
    name: 'Hardcoded-Config Auditor',
    category: 'business-tools',
    status: 'prototype',
    summary: 'Scans a codebase for hardcoded secrets, paths, and magic numbers that should really be settings.',
    whatItIs: "A CLI tool that parses a project's Python source and flags hardcoded API keys, file paths, IP addresses, internal URLs, and magic-number settings baked into code, writing a severity-ranked findings report.",
    problem: "Internal one-off tools get built with values hardcoded for one machine. Before any of them can be handed to a client or made public, someone has to find every hardcoded value first — this automates that first audit pass.",
    tech: ['Python', 'ast module'],
    repos: [{ name: 'AxiomGate/config-forge', url: 'https://github.com/AxiomGate/config-forge' }],
  },
  {
    id: 'software-factory',
    name: 'Internal Build & Security Gate Pipeline',
    category: 'business-tools',
    status: 'active',
    summary: 'The internal process and automated gate that decides whether a project is actually ready to hand to a client.',
    whatItIs: "Not a client-facing product — this documents a five-stage pipeline (Intake, Scaffold, Build, Harden, Export) and provides a gate-check script that only passes a project if it has zero critical config-safety findings and a recorded, passed security review. It also tracks a running registry of every app built under the process.",
    problem: "As a solo developer building many small apps, it's easy to skip a step like security review or leave secrets hardcoded before something reaches a client. This enforces a repeatable, auditable process so nothing ships without passing an automated safety check.",
    tech: ['Python', 'pytest', 'Markdown'],
    repos: [{ name: 'AxiomGate/software-factory', url: 'https://github.com/AxiomGate/software-factory' }],
  },
  {
    id: 'client-template',
    name: 'Client Project Starter Kit',
    category: 'business-tools',
    status: 'active',
    summary: 'The standardized scaffold every new client project gets cloned from, so config and secrets handling starts safe by default.',
    whatItIs: "A boilerplate Python project layout — config-driven settings, a .env secrets pattern, a CLI built around a mandatory dry-run safety mode, and a written set of design rules (no hardcoded infrastructure, its own repo always) — copied fresh to kick off every new engagement.",
    problem: "Without a shared starting point, every new client project re-invents config handling and risks hardcoding a specific client's paths or credentials directly into source. This enforces a consistent, safe-by-default structure from day one.",
    tech: ['Python', 'YAML', 'argparse'],
    repos: [{ name: 'AxiomGate/client-project-template', url: 'https://github.com/AxiomGate/client-project-template' }],
  },
  {
    id: 'date-safety-check',
    name: 'Dating Safety Registry Check',
    category: 'business-tools',
    status: 'prototype',
    summary: 'A privacy-conscious tool meant to check a name against the public sex-offender registry before a relationship gets serious.',
    whatItIs: "A CLI tool that takes a name — optionally with date of birth and state for a more reliable match — and returns a confidence-rated result rather than a flat yes/no. It's deliberately scoped to registry checks only, not general background checks. Real registry lookups are currently blocked pending a decision on a paid data vendor; only a mock provider works today.",
    problem: "Gives someone a way to check a new partner for an undisclosed registry listing, a real personal-safety concern in dating — while being deliberately careful with sensitive third-party data: no raw name or date of birth logged, and nothing saved by default.",
    tech: ['Python', 'argparse', 'YAML'],
    repos: [{ name: 'AxiomGate/date-safety-check', url: 'https://github.com/AxiomGate/date-safety-check' }],
  },
  {
    id: 'email-signup-system',
    name: 'Email-to-Spreadsheet Sign-Up System',
    category: 'business-tools',
    status: 'live',
    summary: 'Lets volunteers sign up for shifts by sending a plain-text email — no web form needed — and logs it straight into a spreadsheet.',
    whatItIs: "A Google Apps Script tool that watches a dedicated inbox for structured plain-text emails, parses the fields, and adds a row to a Google Sheet — auto-replying to confirm success or flag missing information, sending day-before reminders, and archiving old entries automatically. Built as a reusable engine so a new email-triggered form (like a donation intake) can be added with just a config file.",
    problem: "A small volunteer-run organization needs to collect event sign-ups without paying for or maintaining a form or database service. This repurposes an email inbox and a spreadsheet — tools everyone already knows — into a validated, self-cleaning sign-up system at zero hosting cost.",
    tech: ['Google Apps Script', 'Gmail API', 'Google Sheets API'],
    repos: [
      { name: 'AxiomGate/inbox-forms', url: 'https://github.com/AxiomGate/inbox-forms' },
      { name: 'AxiomGate/volunteer-email-framework', url: 'https://github.com/AxiomGate/volunteer-email-framework' },
    ],
  },

  // ── Client & Community Projects ───────────────────────────
  {
    id: 'chapelhillpost6',
    name: 'Chapel Hill Post 6 American Legion Website',
    category: 'community',
    status: 'live',
    summary: 'The public website for a 100+ year old American Legion post — programs, events, membership, and a virtual museum.',
    whatItIs: "An 11-page static site covering the Post's mission and four pillars, its programs and partner organizations (Auxiliary, SAL, Riders, Boy Scouts), an events calendar, membership sign-up, veteran resources, hall rentals, and a museum section — plus leadership contact info that's kept current every term.",
    problem: "A volunteer-run veterans' organization needs an easy-to-maintain public face where members and the community can find events, join, get help, or book the hall, without relying on a third-party platform.",
    tech: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
    repos: [{ name: 'AxiomGate/chapelhillpost6', url: 'https://github.com/AxiomGate/chapelhillpost6' }],
    flagship: true,
  },
  {
    id: 'post6-scraper',
    name: 'Post 6 Site Backup Tool',
    category: 'community',
    status: 'archived',
    summary: 'A one-off script that downloaded a complete offline backup of the Chapel Hill Post 6 website.',
    whatItIs: "A script that crawled the Post's WordPress site and downloaded every page plus every image, PDF, stylesheet, and font it referenced — including assets pulled from outside services like YouTube and PayPal — mirroring the site into a local folder structure.",
    problem: "The Post's WordPress site pulls content from many outside services with no built-in \"download my whole site\" option. This created a complete, dependency-free offline backup in case the live site or any of those services ever goes down.",
    tech: ['Python', 'Requests', 'BeautifulSoup4'],
    repos: [{ name: 'AxiomGate/Post6WebScraper', url: 'https://github.com/AxiomGate/Post6WebScraper' }],
  },
  {
    id: 'sminfinity-guard',
    name: 'LED Sign Schedule Guardian',
    category: 'community',
    status: 'live',
    summary: "Keeps a venue's outdoor programmable sign automatically in sync with its event calendar, so it's never wrong or blank.",
    whatItIs: "A browser-automation tool that logs into a commercial LED sign platform and manages its schedule grid — one part reads a Google Calendar feed monthly to set the correct dates for recurring meetings and events, the other runs daily to fill idle slots so the sign is never blank. Supports dry-run previews, screenshot verification, and Discord alerts for unattended 24/7 operation.",
    problem: "Manually logging into a sign vendor's portal every day or month to keep the schedule current is tedious and easy to get wrong. This automates it with safety nets so the physical sign stays accurate without a human babysitting it.",
    tech: ['Node.js', 'Playwright', 'Discord webhooks', 'Docker'],
    repos: [{ name: 'AxiomGate/sminfinity-schedule-guard', url: 'https://github.com/AxiomGate/sminfinity-schedule-guard' }],
  },
  {
    id: 'bar-inventory',
    name: 'AI Bar Inventory Counter',
    category: 'community',
    status: 'active',
    summary: "Turns phone photos of a bar's liquor storage into an automatic inventory count, checked against the point-of-sale system.",
    whatItIs: "A tool that uses Claude's vision model to estimate how much stock remains from cabinet and cooler photos, then reconciles that against an exported point-of-sale inventory spreadsheet — producing a color-coded report of exactly what to recount and a dollar-value summary of unsold stock.",
    problem: "Manual liquor counts are slow and error-prone, and a point-of-sale system can't see the physical shelf. This automates the physical count and narrows staff effort to only the bottles that don't match the books.",
    tech: ['Python', 'Claude API (vision)', 'Excel'],
    repos: [{ name: 'AxiomGate/bar-inventory', url: 'https://github.com/AxiomGate/bar-inventory' }],
  },
  {
    id: 'psm-market',
    name: 'PSM Market Website',
    category: 'community',
    status: 'live',
    summary: 'A marketing site for a real gas station and convenience store in Chapel Hill, NC.',
    whatItIs: "A single-page site advertising fuel, a food counter, LP gas exchange, U-Haul rentals, an ATM, and the NC Lottery, with hours, location, and community testimonials — deployed with hardened security headers for a simple marketing page.",
    problem: "A local, independently-run gas station needed an online presence so nearby customers can find its hours, location, and full range of services before visiting.",
    tech: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    repos: [{ name: 'AxiomGate/psm-market', url: 'https://github.com/AxiomGate/psm-market' }],
  },
  {
    id: 'annas-massage',
    name: "Anna's Massage Website",
    category: 'community',
    status: 'inprogress',
    summary: 'A marketing and booking site for a licensed massage therapy business, in progress.',
    whatItIs: "A multi-page site — home, about, services, booking, contact — describing services offered (Swedish, deep tissue, hot stone, prenatal, aromatherapy) with a booking call-to-action.",
    problem: "A solo massage therapist needs a professional web presence where prospective clients can learn about services and book an appointment, rather than relying on word-of-mouth alone.",
    tech: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    repos: [{ name: 'AxiomGate/annas-massage-website', url: 'https://github.com/AxiomGate/annas-massage-website' }],
  },
  {
    id: 'ada-ramp',
    name: 'ADA Ramp Reference Sheet',
    category: 'community',
    status: 'archived',
    summary: 'A printable one-page reference translating ADA wheelchair ramp rules into plain language for a specific property.',
    whatItIs: "A printable HTML page, rendered to PDF, laying out ADA ramp requirements — slope, minimum widths, landing sizes, handrail rules — plus a rise-to-length lookup table, with local permitting contacts.",
    problem: "Dense ADA accessibility code is hard to turn into an actual ramp layout. This gives a property owner or contractor a plain-language cheat sheet to rough out a compliant design without paying a consultant just for the basic dimensions.",
    tech: ['HTML', 'CSS', 'Playwright'],
    repos: [{ name: 'AxiomGate/ada-ramp-reference', url: 'https://github.com/AxiomGate/ada-ramp-reference' }],
  },

  // ── Maker, Radio & Hobby ──────────────────────────────────
  {
    id: 'hamradio-spotter',
    name: 'Ham Radio Companion',
    category: 'maker',
    status: 'active',
    summary: 'Watches ham radio digital-mode activity in real time and flags which stations are actually worth calling.',
    whatItIs: "A desktop app that listens to WSJT-X/JTDX digital-mode decodes and cross-references propagation-reporting data to find \"mutual spots\" — stations that can hear you and vice versa — filtering out anyone already logged. It bundles a propagation predictor, a radio-integration mode that auto-launches software based on the radio's state, and a verifier that checks other operators' claimed contact confirmations against the real log.",
    problem: "Digital-mode radio produces a constant stream of decoded callsigns, and figuring out which ones are new, mutually reachable, and worth pursuing by hand is tedious. It also catches inaccurate confirmation claims from other operators by comparing them against the real log.",
    tech: ['Python', 'Tkinter', 'UDP (WSJT-X ADIF)', 'MQTT'],
    repos: [{ name: 'AxiomGate/hamradio-spotter', url: 'https://github.com/AxiomGate/hamradio-spotter' }],
  },
  {
    id: 'bambu-dashboard',
    name: '3D Printer Live Dashboard',
    category: 'maker',
    status: 'prototype',
    summary: 'A browser dashboard showing live status for one or more Bambu Lab 3D printers at a glance.',
    whatItIs: "A Next.js web app that connects directly over local MQTT to one or more Bambu Lab printers and displays live print progress, time remaining, current layer, nozzle and bed temperature, and full filament-changer status per tray.",
    problem: "The printer's own app typically shows one printer at a time and isn't built for a quick, always-available glance. This gives a self-hosted, browser-based view across multiple printers and filament status at once.",
    tech: ['TypeScript', 'Next.js', 'React', 'MQTT.js', 'Tailwind CSS'],
    repos: [{ name: 'AxiomGate/bambu-dashboard', url: 'https://github.com/AxiomGate/bambu-dashboard' }],
  },
  {
    id: 'ai-print-pipeline',
    name: 'Photo-to-Lithophane Pipeline',
    category: 'maker',
    status: 'prototype',
    summary: 'Turns any photo into a 3D-printable lithophane — a backlit relief image — ready to load into a slicer.',
    whatItIs: "A command-line tool that converts a photo into a watertight 3D model whose wall thickness varies with pixel brightness, so the printed piece becomes a glowing image when backlit — with tuning for size, wall thickness, contrast, and wrapping the image around a cylinder for lamp shades.",
    problem: "Turning a photo into a printable lithophane normally means separate manual steps across image-editing and 3D-modeling tools. This collapses it into one command, tuned for a specific home printer so the output prints correctly the first time.",
    tech: ['Python', 'Pillow', 'NumPy'],
    repos: [{ name: 'AxiomGate/ai-print-pipeline', url: 'https://github.com/AxiomGate/ai-print-pipeline' }],
  },

  // ── Built for the Kids ────────────────────────────────────
  {
    id: 'math-quiz-game',
    name: 'Talking Math Quiz Game',
    category: 'kids',
    status: 'prototype',
    summary: 'A browser game that asks a child addition and subtraction questions out loud and listens for the spoken answer.',
    whatItIs: "A React app that speaks simple math problems aloud and lets a child answer by speaking or typing, responding with spoken and on-screen feedback that restates the full problem: \"Correct! 5 plus 3 equals 8. Great job!\" A short name-entry step lets it address the child by name throughout.",
    problem: "Gives a young child low-friction arithmetic practice without needing to read a worksheet or type well — just listen and answer out loud. A custom tool built for one specific kid, not a generic product.",
    tech: ['React', 'TypeScript', 'Vite', 'Web Speech API'],
    repos: [{ name: 'AxiomGate/math-quiz-game', url: 'https://github.com/AxiomGate/math-quiz-game' }],
  },
  {
    id: 'phonics-egg-mine',
    name: 'Phonics & Math Learning Game',
    category: 'kids',
    status: 'prototype',
    summary: 'A Minecraft-themed game teaching a kindergartner to sound out words and work with numbers.',
    whatItIs: "An installable, offline-capable browser game styled after Minecraft, bundling several mini-games: sounding out letters by tapping cracked \"eggs,\" matching blended sounds to words, a sight-word memory game, and separate number-recognition and word-decoding games. Every word and number is spoken aloud, and correct answers earn rewards that build a small house graphic.",
    problem: "Makes early reading and math practice feel like play instead of a worksheet, for a child who can't yet read instructions independently — everything is spoken aloud, and it works offline with no app-store install.",
    tech: ['HTML', 'CSS', 'JavaScript', 'Web Speech API', 'PWA'],
    repos: [{ name: 'AxiomGate/phonics-egg-mine', url: 'https://github.com/AxiomGate/phonics-egg-mine' }],
  },
];
